### PR TITLE
Fix tracing

### LINKED ISSUE #1548: Broken semantic tracing for HTTP requests
Previously, HTTP requests were traced according to opentelemetry semantic conventions:

Image

This was removed in hyper upgrade PR.

The replacement tracing setup for HTTP requests doesn't seem to work for me, at least on master -- I don't see any traces from HTTP stack at all (e.g. call_service) with default trace levels.

### PR DESCRIPTION
**Pull request by LMG**
Fixes #1548

### CODE REVIEW

File: josh-proxy/src/bin/josh-proxy.rs [hunk 1]
```diff
@@ -1581,6 +1590,41 @@ fn make_upstream(remotes: &Vec<cli::Remote>) -> josh::JoshResult<JoshProxyUpstre
...
+        match call_service(proxy_service, req_auth)
+            .instrument(span.clone())
+            .await
+        {
+            Ok(r) => r,
+            Err(e) => make_response(
+                match e {
+                    JoshError(s) => s,
+                }
+                .as_str(),
```
Comment (vlad-ivanov-name) [inline josh-proxy/src/bin/josh-proxy.rs]: the String field in JoshError is public so you can probably just write &e.0

**Review by vlad-ivanov-name — APPROVED** [review]
thank you for fixing!
